
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Khofi Muffin
 */
public class room extends javax.swing.JFrame {

    String str, str1, xxx;
    int choice,z,pin=1234,counter=0,a=3;
    int k,t,s,tab=50000;

    /**
     * Creates new form room
     */
    public room() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transfer");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 260, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LAKUKAN TRANSAKSI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 10, 240, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Penarikan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 380, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bantuan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 260, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Exit");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 380, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Informasi Saldo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 140, 124, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Penyetoran");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 140, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(80, 20, 430, 420);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 390, 60, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 150, 60, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 270, 60, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton4.setText(">");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(510, 150, 60, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton5.setText(">");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(510, 270, 60, 50);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton6.setText(">");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(510, 390, 60, 50);

        setBounds(0, 0, 610, 503);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : " + tab); //informasi saldo
        z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM KHOFIFAH SYARIAH", JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
        if(z==1){
            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM KHOFIFAH SYARIAH, ambil kartu ATM Anda.");
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Cara Penggunaan Aplikasi\n"
                + "[1] Masukkan PIN dengan benar\n[2] Bertransaksilah dengan benar sesuai pilihan\n"
                + "[3] Gunakan Uang sesuai kebutuhan dan rajinlah menabung\n ","INFO",1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: " ); //menabung
        s = Integer.parseInt(str1);
        setor hasil = new setor();
        hasil.menabung(tab, s);
        tab =hasil.getsaldo();
        z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM KHOFIFAH SYARIAH", JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
        if(z==1){
            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM KHOFIFAH SYARIAH, ambil kartu ATM Anda.");
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : " ); //pengambilan
        t = Integer.parseInt(str1);
        tarik mengambil = new tarik();
        mengambil.ambil(tab,t);
        tab =mengambil.getsaldo();
        z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM KHOFIFAH SYARIAH", JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
        if(z==1){
            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM KHOFIFAH SYARIAH, ambil kartu ATM Anda.");
            System.exit(0);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        z=JOptionPane.showConfirmDialog(null,"Anda ingin keluar?","Keluar", JOptionPane.YES_NO_OPTION, 0);
        if(z==0){
            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM KHOFIFAH SYARIAH, ambil kartu ATM Anda.");
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        xxx = JOptionPane.showInputDialog(null,"Masukkan no. rekening penerima : " ); //penerima
        k = Integer.parseInt(xxx);
        

        if(xxx!=""){
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah transfer : " ); //pengambilan
        t = Integer.parseInt(str1);
        transfer take = new transfer();
        take.trans(tab,t,k);
        tab =take.getsaldo();}
        
        
        
        z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM KHOFIFAH SYARIAH", JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
        if(z==1){
            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM KHOFIFAH SYARIAH, ambil kartu ATM Anda.");
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class setor {
    private int saldo;
    public void menabung (int bal, int s){
        if(s%100!=0)
            JOptionPane.showMessageDialog(null, "Mesin ATM BRI tidak menerima uang koin \nSilahkan ulangi kembali!","Transaksi Gagal", 0);
        else if(s<50000)
            JOptionPane.showMessageDialog(null, "Besaran minimal setor tunai adalah Rp 50000,00","ERROR",0);
        else if(s>=50000){
            saldo = bal+s;
            JOptionPane.showMessageDialog(null, "Saldo Anda saat ini sebesar : "+saldo);
        }
    }
    
    public int getsaldo(){
        return saldo;
        }
    }

    private static class tarik {
    private int saldo;
    public void ambil(int tab, int t){
        if(t%100!=0)
            JOptionPane.showMessageDialog(null, "Mesin ATM BRI tidak menerima uang koin \nSilahkan ulangi lagi","Transaksi Gagal",0);
        else{
            if(t>tab)
                JOptionPane.showMessageDialog(null,"Saldo Anda tidak mencukupi \nSilahkan lakukan penyetoran", "Transaksi Gagal", 0);
            else if(t<50000)
                JOptionPane.showMessageDialog(null,"Besaran minimal pengambilan tunai adalah Rp.50000","Transaksi Gagal",0);
            else{
                saldo = tab-t;
                JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : "+saldo);;
                if(tab<=50000)
                    JOptionPane.showMessageDialog(null,"Saldo minimal harus Rp. 50000,00, Segera lakukan penyetoran untuk menghindari penutuan akun.","CAUTION",2);
            }
        }
    }
    public int getsaldo(){
        return saldo;
    }
        
    }  

    private static class transfer {
    private int saldo;
    private void trans(int tab, int t, int k){
        if(t%100!=0)
            JOptionPane.showMessageDialog(null, "Besaran minimal pengiriman adalah Rp.5000","Transaksi Gagal",0);
        else{
            if(t>tab)
                JOptionPane.showMessageDialog(null,"Saldo Anda tidak mencukupi \nSilahkan lakukan penyetoran", "Transaksi Gagal", 0);
            else{
                saldo = tab-t;
                JOptionPane.showMessageDialog(null,
                         "Transfer ke                   : "+k
                        +"\nJumlah transfer             : "+t
                        +"\nSaldo Anda saat ini sebesar : "+saldo);
                if(tab<=50000)
                    JOptionPane.showMessageDialog(null,"Saldo minimal harus Rp. 50000,00, Segera lakukan penyetoran untuk menghindari penutupan akun.","CAUTION",2);
            }
        }
    }
    public int getsaldo(){
        return saldo;
    }
    }
}
